namespace:
  name: prod
 
service:
  port: 7111
  type: ClusterIP
  targetPort: 3111
  protocol: TCP

image:
  repository: magicnote/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 350m
  limits:
    memory: 256Mi
    cpu: 500m

containerPort: 3111
livenessProbe:
  path: /healthz
  port: 3111
readinessProbePath:
  path: /healthz
  port: 3111