namespace:
  name: staging
 
service:
  port: 5111
  type: ClusterIP
  targetPort: 3111
  protocol: TCP

image:
  repository: magicnote/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111
livenessProbe:
  path: /healthz
  port: 3111
readinessProbePath:
  path: /healthz
  port: 3111