namespace:
  name: sandbox
 
service:
  port: 4111
  type: ClusterIP
  targetPort: 3111
  protocol: TCP

image:
  repository: magicnote/techtrends
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111
livenessProbe:
  path: /healthz
  port: 3111
readinessProbePath:
  path: /healthz
  port: 3111